services:
  - type: web
    name: badmintondaddy
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATA_DIR
        value: /var/data
    disk:
      name: birthday-data
      mountPath: /var/data
      sizeGB: 1
